### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by ztj666** [4Q-s-r-o/ota_update#1]
18:34:11.068 130 info flutter.tools [        ] I/flutter (31605): MissingPluginException(No implementation found for method listen on channel sk.fourq.ota_update)

**Comment by ethael** [comment]
thanks for the bug reports. can you please give us result of flutter doctor and last exception stacktrace?

**Comment by ztj666** [comment]
18:56:04.377 105 info flutter.tools [  +46 ms] I/flutter (11012): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
18:56:04.379 106 info flutter.tools [   +6 ms] I/flutter (11012): The following MissingPluginException was thrown while activating platform stream on channel
18:56:04.379 107 info flutter.tools [        ] I/flutter (11012): sk.fourq.ota_update:
18:56:04.379 108 info flutter.tools [        ] I/flutter (11012): MissingPluginException(No implementation found for method listen on channel sk.fourq.ota_update)
18:56:04.411 109 info flutter.tools [  +30 ms] I/flutter (11012): When the exception was thrown, this was the stack:
18:56:04.533 110 info flutter.tools [ +120 ms] I/flutter (11012): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:291:7)
18:56:04.533 111 info flutter.tools [        ] I/flutter (11012): <asynchronous suspension>
18:56:04.533 112 info flutter.tools [        ] I/flutter (11012): #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:437:29)
18:56:04.533 113 info flutter.tools [        ] I/flutter (11012): <asynchronous suspension>
18:56:04.533 114 info flutter.tools [        ] I/flutter (11012): #9      MyLoginState.build.<anonymous closure>.<anonymous closure> (package:lysj_property_app/main.dart:221:24)
18:56:04.533 115 info flutter.tools [        ] I/flutter (11012): #18     _withClient (package:http/http.dart)
18:56:04.533 116 info flutter.tools [        ] I/flutter (11012): <asynchronous suspension>
18:56:04.533 117 info flutter.tools [        ] I/flutter (11012): #19     post (package:http/http.dart:70:3)
18:56:04.533 118 info flutter.tools [        ] I/flutter (11012): #20     MyLoginState.build.<anonymous closure> (package:lysj_property_app/main.dart:202:11)
18:56:04.533 119 info flutter.tools [        ] I/flutter (11012): #29     DataUtils.getAccessToken (package:lysj_property_app/util/DataUtils.dart)
18:56:04.533 120 info flutter.tools [        ] I/flutter (11012): <asynchronous suspension>
18:56:04.533 121 info flutter.tools [        ] I/flutter (11012): #30     MyLoginState.build (package:lysj_property_app/main.dart:195:17)
18:56:04.533 122 info flutter.tools [        ] I/flutter (11012): #31     StatefulElement.build (package:flutter/src/widgets/framework.dart:3787:27)
18:56:04.533 123 info flutter.tools [        ] I/flutter (11012): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:15)
18:56:04.533 124 info flutter.tools [        ] I/flutter (11012): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
18:56:04.533 125 info flutter.tools [        ] I/flutter (11012): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
18:56:04.533 126 info flutter.tools [        ] I/flutter (11012): #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3826:11)
18:56:04.533 127 info flutter.tools [        ] I/flutter (11012): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
18:56:04.533 128 info flutter.tools [        ] I/flutter (11012): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
18:56:04.533 129 info flutter.tools [        ] I/flutter (11012): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
18:56:04.533 130 info flutter.tools [        ] I/flutter (11012): #39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4838:14)
18:56:04.533 131 info flutter.tools [        ] I/flutter (11012): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
18:56:04.533 132 info flutter.tools [        ] I/flutter (11012): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
18:56:04.533 133 info flutter.tools [        ] I/flutter (11012): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
18:56:04.533 134 info flutter.tools [        ] I/flutter (11012): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
18:56:04.533 135 info flutter.tools [        ] I/flutter (11012): #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
18:56:04.533 136 info flutter.tools [        ] I/flutter (11012): #45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
18:56:04.533 137 info flutter.tools [        ] I/flutter (11012): #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
18:56:04.533 138 info flutter.tools [        ] I/flutter (11012): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
18:56:04.534 139 info flutter.tools [        ] I/flutter (11012): #48     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4838:14)
18:56:04.534 140 info flutter.tools [        ] I/flutter (11012): #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
18:56:04.534 141 info flutter.tools [        ] I/flutter (11012): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
18:56:04.534 142 info flutter.tools [        ] I/flutter (11012): #51     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4838:14)
18:56:04.534 143 info flutter.tools [        ] I/flutter (11012): #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
18:56:04.534 144 info flutter.tools [        ] I/flutter (11012): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
18:56:04.534 145 info flutter.tools [        ] I/flutter (11012): #54     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4838:14)
18:56:04.534 146 info flutter.tools [        ] I/flutter (11012): #55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
18:56:04.534 147 info flutter.tools [        ] I/flutter (11012): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
18:56:04.534 148 info flutter.tools [        ] I/flutter (11012): #57     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4838:14)
18:56:04.534 149 info flutter.tools [        ] I/flutter (11012): #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
18:56:04.534 150 info flutter.tools [        ] I/flutter (11012): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
18:56:04.534 151 info flutter.tools [        ] I/flutter (11012): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
18:56:04.536 152 info flutter.tools [        ] I/flutter (11012): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
18:56:04.536 153 info flutter.tools [        ] I/flutter (11012): #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
18:56:04.536 154 info flutter.tools [        ] I/flutter (11012): #63     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3826:11)
18:56:04.536 155 info flutter.tools [        ] I/flutter (11012): #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
18:56:04.536 156 info flutter.tools [        ] I/flutter (11012): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
18:56:04.536 157 info flutter.tools [        ] I/flutter (11012): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
18:56:04.538 158 info flutter.tools [        ] I/flutter (11012): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
18:56:04.538 159 info flutter.tools [        ] I/flutter (11012): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
18:56:04.538 160 info flutter.tools [        ] I/flutter (11012): #69     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
18:56:04.538 161 info flutter.tools [        ] I/flutter (11012): #70     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
18:56:04.538 162 info flutter.tools [        ] I/flutter (11012): #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
18:56:04.538 163 info flutter.tools [        ] I/flutter (11012): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
18:56:04.538 164 info flutter.tools [        ] I/flutter (11012): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
18:56:04.538 165 info flutter.tools [        ] I/flutter (11012): #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
18:56:04.538 166 info flutter.tools [        ] I/flutter (11012): #75     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
18:56:04.538 167 info flutter.tools [        ] I/flutter (11012): #76     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3826:11)
18:56:04.538 168 info flutter.tools [        ] I/flutter (11012): #77     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
18:56:04.538 169 info flutter.tools [        ] I/flutter (11012): #78     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
18:56:04.538 170 info flutter.tools [        ] I/flutter (11012): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
18:56:04.538 171 info flutter.tools [        ] I/flutter (11012): #80     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4838:14)
18:56:04.538 172 info flutter.tools [        ] I/flutter (11012): #81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
18:56:04.538 173 info flutter.tools [        ] I/flutter (11012): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
18:56:04.538 174 info flutter.tools [        ] I/flutter (11012): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
18:56:04.540 175 info flutter.tools [        ] I/flutter (11012): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
18:56:04.540 176 info flutter.tools [        ] I/flutter (11012): #85     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
18:56:04.540 177 info flutter.tools [        ] I/flutter (11012): #86     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
18:56:04.540 178 info flutter.tools [        ] I/flutter (11012): #87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
18:56:04.540 179 info flutter.tools [   +1 ms] I/flutter (11012): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
18:56:04.540 180 info flutter.tools [        ] I/flutter (11012): #89     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4838:14)
18:56:04.540 181 info flutter.tools [        ] I/flutter (11012): #90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
18:56:04.540 182 info flutter.tools [        ] I/flutter (11012): #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
18:56:04.540 183 info flutter.tools [        ] I/flutter (11012): #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
18:56:04.542 184 info flutter.tools [        ] I/flutter (11012): #93     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
18:56:04.542 185 info flutter.tools [        ] I/flutter (11012): #94     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
18:56:04.542 186 info flutter.tools [        ] I/flutter (11012): #95     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3826:11)
18:56:04.542 187 info flutter.tools [        ] I/flutter (11012): #96     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
18:56:04.542 188 info flutter.tools [        ] I/flutter (11012): #97     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
18:56:04.542 189 info flutter.tools [        ] I/flutter (11012): #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
18:56:04.542 190 info flutter.tools [        ] I/flutter (11012): #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
18:56:04.542 191 info flutter.tools [        ] I/flutter (11012): #100    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
18:56:04.542 192 info flutter.tools [        ] I/flutter (11012): #101    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
18:56:04.542 193 info flutter.tools [        ] I/flutter (11012): #102    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
18:56:04.542 194 info flutter.tools [        ] I/flutter (11012): #103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
18:56:04.542 195 info flutter.tools [        ] I/flutter (11012): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
18:56:04.542 196 info flutter.tools [        ] I/flutter (11012): #105    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4838:14)
18:56:04.544 197 info flutter.tools [   +2 ms] I/flutter (11012): #106    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
18:56:04.544 198 info flutter.tools [        ] I/flutter (11012): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
18:56:04.546 199 info flutter.tools [        ] I/flutter (11012): #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
18:56:04.546 200 info flutter.tools [        ] I/flutter (11012): #109    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
18:56:04.546 201 info flutter.tools [        ] I/flutter (11012): #110    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
18:56:04.546 202 info flutter.tools [        ] I/flutter (11012): #111    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
18:56:04.546 203 info flutter.tools [        ] I/flutter (11012): #112    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
18:56:04.546 204 info flutter.tools [        ] I/flutter (11012): #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
18:56:04.546 205 info flutter.tools [        ] I/flutter (11012): #114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
18:56:04.546 206 info flutter.tools [        ] I/flutter (11012): #115    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
18:56:04.546 207 info flutter.tools [        ] I/flutter (11012): #116    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
18:56:04.546 208 info flutter.tools [        ] I/flutter (11012): #117    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3826:11)
18:56:04.546 209 info flutter.tools [        ] I/flutter (11012): #118    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
18:56:04.546 210 info flutter.tools [        ] I/flutter (11012): #119    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
18:56:04.548 211 info flutter.tools [        ] I/flutter (11012): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
18:56:04.548 212 info flutter.tools [        ] I/flutter (11012): #121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
18:56:04.548 213 info flutter.tools [        ] I/flutter (11012): #122    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
18:56:04.548 214 info flutter.tools [        ] I/flutter (11012): #123    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)

**Comment by ztj666** [comment]
java.lang.NoSuchMethodError: No virtual method checkSelfPermission(Ljava/lang/String;)I in class Landroid/app/Activity; or its super classes (declaration of 'android.app.Activity' appears in /system/framework/framework.jar:classes2.dex)

**Comment by ztj666** [comment]
12-13 21:59:46.941 439-3234/? D/FFMPEG: android source close
12-13 22:10:39.234 3174-3197/? I/flutter: permission is1 PermissionGroup.sensors
12-13 22:10:39.235 3174-3174/? D/permissions_handler: No permissions found in manifest for: SENSORS
12-13 22:10:42.920 118-118/? I/DEBUG:     #00 pc 000740b6  /system/lib/libc.so (tgkill+22)
12-13 22:10:42.920 118-118/? I/DEBUG:     #01 pc 000221ab  /system/lib/libc.so (pthread_kill+155)
12-13 22:10:42.920 118-118/? I/DEBUG:     #02 pc 00023a24  /system/lib/libc.so (raise+36)
12-13 22:10:42.920 118-118/? I/DEBUG:     #03 pc 0001be24  /system/lib/libc.so (abort+84)
12-13 22:10:42.920 118-118/? I/DEBUG:     #04 pc 000a1862  /data/app/com.sjfw365.yohome-1/lib/x86/libflutter.so
12-13 22:10:42.920 118-118/? I/DEBUG:     #05 pc 000938e0  /data/app/com.sjfw365.yohome-1/lib/x86/libflutter.so
12-13 22:10:42.920 118-118/? I/DEBUG:     #06 pc 00092773  /data/app/com.sjfw365.yohome-1/lib/x86/libflutter.so
12-13 22:10:42.920 118-118/? I/DEBUG:     #07 pc 000dc5e5  /data/app/com.sjfw365.yohome-1/lib/x86/libflutter.so
12-13 22:10:42.920 118-118/? I/DEBUG:     #08 pc 000a3737  /data/app/com.sjfw365.yohome-1/lib/x86/libflutter.so
12-13 22:10:42.920 118-118/? I/DEBUG:     #09 pc 000a3682  /data/app/com.sjfw365.yohome-1/lib/x86/libflutter.so
12-13 22:10:42.920 118-118/? I/DEBUG:     #10 pc 000a59ee  /data/app/com.sjfw365.yohome-1/lib/x86/libflutter.so
12-13 22:10:42.920 118-118/? I/DEBUG:     #11 pc 00019700  /system/lib/libutils.so (android::SimpleLooperCallback::handleEvent(int, int, void*)+32)
12-13 22:10:42.920 118-118/? I/DEBUG:     #12 pc 0001b892  /system/lib/libutils.so (android::Looper::pollInner(int)+690)
12-13 22:10:42.920 118-118/? I/DEBUG:     #13 pc 0001baa7  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+55)
12-13 22:10:42.920 118-118/? I/DEBUG:     #14 pc 000c8787  /system/lib/libandroid_runtime.so (android::NativeMessageQueue::pollOnce(_JNIEnv*, int)+71)
12-13 22:10:42.920 118-118/? I/DEBUG:     #15 pc 000c87ea  /system/lib/libandroid_runtime.so
12-13 22:10:43.461 699-4094/system_process W/ActivityManager: Exception thrown during pause
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:550)
        at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:704)
        at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:825)
        at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2726)
        at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2583)
        at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2497)
        at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11566)
        at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11463)
        at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12147)
        at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:11658)
        at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)

**Comment by iambudi** [comment]
`flutter clean
`
 after rebuilding does not throw the error 👏

**Comment by MartinHlavna** [comment]
Hi @ztj666 does ```flutter clean``` solve your problem? Or does it still persists?

**Comment by ethael** [comment]
closing as flutter clean likely resolved the problem
