### ISSUE TITLE
Error receiving broadcast Intent android.intent.action.DOWNLOAD_COMPLETE

### ISSUE THREAD

**Issue by AlexVincent525** [4Q-s-r-o/ota_update#10]
Hi there!
I'm using this plugin as update tool, and when I just about to finish downloading, as logs displayed at 99%, the app shutdown.
My code was almost the same as the example, but not in `main.dart`, and using custom event to handle the event change.
```
static Future<void> tryOtaUpdate() async {
  try {
    if (Platform.isAndroid) {
      OtaUpdate().execute(Api.latestAndroid).listen((OtaEvent event) {
        Constants.eventBus.fire(new OTAEvent(event));
      });
    } else if (Platform.isIOS) {
      OtaUpdate().execute(Api.latestIOS).listen((OtaEvent event) {
        Constants.eventBus.fire(new OTAEvent(event));
      });
    }
  } catch (e) {
    print('Failed to make OTA update. Details: $e');
  }
}
```
```
class OTAEvent {
  OtaEvent otaEvent;
  OTAEvent(OtaEvent _otaEvent) {
    this.otaEvent = _otaEvent;
  }
}
```
```
eventBus.on<OTAEvent>().listen((event) {
  if (this.mounted) {
    setState(() {
      this.otaEvent = event.otaEvent;
    });
    print('OTA status: ${this.otaEvent.status} : ${this.otaEvent.value}');
  }
});
```
```Dart
I/flutter (27797): OTA status: OtaStatus.DOWNLOADING : 99
E/AndroidRuntime(27797): FATAL EXCEPTION: main
E/AndroidRuntime(27797): Process: cn.xxx.xxx.xxxxxxx, PID: 27797
E/AndroidRuntime(27797): java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=cn.xxx.xxx.xxxxxxx (has extras) } in sk.fourq.otaupdate.OtaUpdatePlugin$1@50892f
```

**Comment by MartinHlavna** [comment]
Hi,
can you please provide output from `flutter doctor -v`? Looks like `DOWNLOAD_COMPLETE`  could not be delivered from android download manager to the plugin listener.

Is logcat showing any StackTrace? That would be helpful.

**Comment by AlexVincent525** [comment]
Hi, it's been a month since this issue has been created, and currently I'm not using this package, so I will be back when I test this again, cause I'm busy in other things, sorry.
Flutter version is 1.2.1 when this happened.

**Comment by MartinHlavna** [comment]
Does the problem still persists in 2.0.0?

**Comment by shaxxx** [comment]
Bug still exists in 2.0.1
![error](https://user-images.githubusercontent.com/1778875/68300046-44103600-009d-11ea-94ff-303102317786.jpg)

**Comment by shaxxx** [comment]
Ok, after having success with example project I was able to pinpoint the problem.
It was misconfiguration on my side, in AndroidManifest.xml "provider" node should go inside "application" node, not in root node.

As this error is similar to original poster error I suppose it's the same thing. 
I believe this can be closed.

**Comment by MartinHlavna** [comment]
Hi, thanks for the info. I will update the docs.

**Comment by MartinHlavna** [comment]
Documentation updated.

Thanks for the feedback.

**Comment by mHassan20896** [comment]
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE

I am getting this even when Provider is inside application tag
