### ISSUE TITLE
How to catch the error when the network speed is not good?

### ISSUE THREAD

**Issue by LYJGIS** [4Q-s-r-o/ota_update#101]
How to catch the error when the network speed is not good? The default connection, read and write time of **OkHttpClient** in OtaUpdate is **10 seconds.** When the network is poor, it is likely that the connection, read or write time will exceed 10 seconds. In this case, the error cannot be caught.

**Comment by LYJGIS** [comment]
My code like this,but no log is printed.
`      OtaUpdate().execute(fullpath,
        destinationFilename:appname,
      ).listen((OtaEvent event) {
        var curpercent=event.value;
        var curstatus=event.status;
        print('当前状态：$curstatus。 已下载: $curpercent %');
        switch(event.status){
          case OtaStatus.DOWNLOADING://下载中
            if(null!=event.value){
              progress= double.tryParse(event.value!)!/100;
              if(progress> 1.0001){
                dialog!.dismiss();
                progress = 0;
              }
              if(middenprogress!=progress){
                dialog!.update(progress);
                middenprogress=progress;
              }
            }
            break;
          case OtaStatus.INSTALLING: //安装中
            break;
          case OtaStatus.PERMISSION_NOT_GRANTED_ERROR: // 权限错误
            print('权限错误。更新失败，请稍后再试');
            break;
          case OtaStatus.ALREADY_RUNNING_ERROR: // 运行中的错误
            print('运行中的错误。更新失败，请稍后再试');
            break;
          case OtaStatus.DOWNLOAD_ERROR: // 下载错误
            print('下载错误。更新失败，请稍后再试');
            break;
          case OtaStatus.CHECKSUM_ERROR: // 鉴权错误
            print('鉴权错误。更新失败，请稍后再试');
            break;
          case OtaStatus.INTERNAL_ERROR: // 安装错误
            print('安装错误。更新失败，请稍后再试');
            break;
          default: // 其他问题
            print('下载失败。其他问题');
            break;
        }
      },
      );
    } catch (e) {
      print('下载失败。 失败原因: $e');
    };`

**Comment by LYJGIS** [comment]
My code like this,but no log is printed.
![catch null](https://user-images.githubusercontent.com/42628059/222028618-4b2ef20b-2078-49ce-9926-011a5fba1722.png)

**Comment by MartinHlavna** [comment]
From my testing it looks like connection timeouts are working correctly. If the issue persist, please try to setup testing server that will simulate and reproduce your issue. That way we can pinpoint the problem more precisely.
