### ISSUE TITLE
Application is not installed

### ISSUE THREAD

**Issue by BOFOII** [4Q-s-r-o/ota_update#105]
![20230706_070601](https://github.com/4Q-s-r-o/ota_update/assets/79498377/516acdad-a939-44b4-9d4d-d42d35c7453e)

I'm sure all these configurations are correct, but why am I getting an error like this? cannot overwrite the application

**Comment by BOFOII** [comment]
sorry it was my fault for compiling on a different device

**Comment by igorvidottof** [comment]
> sorry it was my fault for compiling on a different device

What do you mean by that? I have the same problem.
