### ISSUE TITLE
Doesnt trigger an installation intent when download complete when app is running in background

### ISSUE THREAD

**Issue by hoangpv-3229** [4Q-s-r-o/ota_update#106]
If the app is running in background, when the download is completed, no installation intent is triggered

**Comment by MartinHlavna** [comment]
Foreground and background execution is out of the scope of this package. If you want to execute package in background you can for example use [workmanager](https://pub.dev/packages/workmanager) package, however this was not tested.

The main problem is that android suspends foreground code after some time in background. To solve this we would have to implement either native work manager, or (maybe) background service.

We could accept well written PR, though.
