### ISSUE TITLE
Multiple Flutter apps with ota_update plugin fails to install

### ISSUE THREAD

**Issue by apgapg** [4Q-s-r-o/ota_update#12]
If i implement ota_update in one app and installs it, and if i again use this plugin in another flutter app then the other app fails to install giving this error message
`[INSTALL_FAILED_CONFLICTING_PROVIDER: Package couldn't be installed in /data/app/com.*cause provider name sk.fourq.ota_update.provider (in package com.*.demo) is already used by com.*.demo]`

(* package name hidden)

This error arises due to same authorities in more than one app ie 'sk.fourq.ota_update.provider'. This can be resolved if one changes the authorities in getUriForFile method in OtaUpdatePlugin.
For this i need to manually add the git repo of this project in my app.

**Comment by sirfarmalot** [comment]
@apgapg how did you manually add the git repo?

Can you explain that workaround more....?

thanks!

**Comment by MartinHlavna** [comment]
Thanks for the report.

Thinking about it, Solution would be making provider authority more dynamic. Looks like [open_file](https://github.com/crazecoder/open_file) plugin has solved same issue with file provider.

**Comment by MartinHlavna** [comment]
Version 2.0.0  should now support this out of the box. Although it is breaking change so migration in AndroidManifest is required. See CHANGELOG.md for more information.
