### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method checkSelfPermission(Ljava/lang/String;)

### ISSUE THREAD

**Issue by akkolyasnikov** [4Q-s-r-o/ota_update#15]
E/flutter (12613): 	at android.app.ActivityThread.main(ActivityThread.java:5667)
E/flutter (12613): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (12613): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/flutter (12613): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:962)
E/flutter (12613): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
E/flutter (12613):
F/flutter (12613): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env).
F/libc    (12613): Fatal signal 6 (SIGABRT), code -6 in tid 12613

 flutter doctor -v
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.592], locale ru-RU)
    • Flutter version 1.7.8+hotfix.3 at C:\flutter
    • Framework revision b712a172f9 (2 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\yona\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\yona\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • TIT L01 • ################ • android-arm64 • Android 5.1 (API 22)

! Doctor found issues in 1 category.

**Comment by MartinHlavna** [comment]
Hi, thanks for the report. Can you please test this on new version 2.0.1? (will be published soon)

Also full stack trace would be helpful.

**Comment by MartinHlavna** [comment]
Closing as there was no response for 3 months. If the problem still persist comment and we will reopen it.
