### ISSUE TITLE
Get a negative progress value when downloading.

### ISSUE THREAD

**Issue by scofield-hello** [4Q-s-r-o/ota_update#16]
I got a negative progress value  when downloading the apk file.

**Comment by lyz3291** [comment]
The size of apk file is too large.

**Comment by scofield-hello** [comment]
the progress in Notification of DownloadManager was positive number

**Comment by bhjSky** [comment]
Modified code（android）:
   Bundle bundle = (Bundle) msg.obj;
   progressSink.success(Arrays.asList("" + OtaStatus.DOWNLOADING.ordinal(), "" + ((bundle.getLong("down") * 100) / bundle.getLong("size"))));


  long bytes_downloaded = c.getLong(c.getColumnIndex(DownloadManager.COLUMN_BYTES_DOWNLOADED_SO_FAR));
                    long bytes_total = c.getLong(c.getColumnIndex(DownloadManager.COLUMN_TOTAL_SIZE_BYTES));
                    if (progressSink != null) {
                        Message message = new Message();
                        Bundle bundle = new Bundle();
                        bundle.putLong("down",bytes_downloaded);
                        bundle.putLong("size",bytes_total);
                        message.obj = bundle;
                        handler.sendMessage(message);
                    }

**Comment by MartinHlavna** [comment]
@bhjSky Thanks for the possible solution. Do you want to do PR? Or I should adopt code from your comment.

**Comment by 18487115313** [comment]
> 修改后的代码（android）：
> Bundle bundle =（Bundle）msg.obj;
> progressSink.success（Arrays.asList（“” + OtaStatus.DOWNLOADING.ordinal（），“ +（（bundle.getLong（” down“）* 100）/ bundle.getLong（” size“）））））;;
> 
> 长字节下载= c.getLong（c.getColumnIndex（DownloadManager.COLUMN_BYTES_DOWNLOADED_SO_FAR））;
> 长字节总数= c.getLong（c.getColumnIndex（DownloadManager.COLUMN_TOTAL_SIZE_BYTES））;
> 如果（progressSink！= null）{
> 消息=新消息（）;
> Bundle bundle = new Bundle（）;
> bundle.putLong（“ down”，bytes_downloaded）;
> bundle.putLong（“ size”，bytes_total）;
> message.obj =捆绑包;
> handler.sendMessage（message）;
> }
这个会出现 bundle.getLong（” size“）这个是0,  除数不能为0

**Comment by bhjSky** [comment]
> > 修改后的代码（android）：
> > Bundle bundle =（Bundle）msg.obj;
> > progressSink.success（Arrays.asList（“” + OtaStatus.DOWNLOADING.ordinal（），“ +（（bundle.getLong（” down“）* 100）/ bundle.getLong（” size“）））））;;
> > 长字节下载= c.getLong（c.getColumnIndex（DownloadManager.COLUMN_BYTES_DOWNLOADED_SO_FAR））;
> > 长字节总数= c.getLong（c.getColumnIndex（DownloadManager.COLUMN_TOTAL_SIZE_BYTES））;
> > 如果（progressSink！= null）{
> > 消息=新消息（）;
> > Bundle bundle = new Bundle（）;
> > bundle.putLong（“ down”，bytes_downloaded）;
> > bundle.putLong（“ size”，bytes_total）;
> > message.obj =捆绑包;
> > handler.sendMessage（message）;
> > }
> > 这个会出现 bundle.getLong（” size“）这个是0,  除数不能为0

When the total number of progress bars is 0, the progress bar will not be updated。
if(bundle.getLong（” size“）!=0){
progressSink.success（Arrays.asList（“” + OtaStatus.DOWNLOADING.ordinal（），“ +（（bundle.getLong（” down“）* 100）/ bundle.getLong（” size“）））））;
}
If the total number of frequent progress bars is 0, please consider the problems of network fluctuation and abnormal downloading of files.

**Comment by MartinHlavna** [comment]
Fixed in 2.0.3
