### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by shaxxx** [4Q-s-r-o/ota_update#19]
Readme is missing instruction to create filepaths.xml file.
Relative path to project root and file content should be specified. 
Also, short info where it's used and why should be specified.

In instructions for modifying AndroidManifest.xml file i believe it would be worth mentioning that provider node goes inside application node and provide link to AndroidManifest.xml file in example.

Thanks for the plugin! :)

**Comment by MartinHlavna** [comment]
Documentation updated.

Thanks for the feedback.

**Comment by shaxxx** [comment]
I apologize, but I forgot to mention extra `try` line in README that makes example incorrect.
Invalid extra try on line 20, entire line should be removed.

**Comment by MartinHlavna** [comment]
Thanks I removed it
