### ISSUE TITLE
ios can't run 

### ISSUE THREAD

**Issue by ginoz** [4Q-s-r-o/ota_update#2]
implicit conversion of 'int' to 'id _Nullable' is disallowed with ARC

**Comment by MartinHlavna** [comment]
Hi, can you please provide output from ```flutter doctor -v```, along with iOS version used?

iOS support was only briefly tested and it may not work correctly at this time. It is currently not in our top priority list though, so I can't tell when we can look at this. We will be happy to merge PR if someone can look at this in meantime.
