### ISSUE TITLE
PlatformException

### ISSUE THREAD

**Issue by gxh-apologize** [4Q-s-r-o/ota_update#27]
`
I/flutter (22346): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
I/flutter (22346): The following PlatformException was thrown while activating platform stream on channel
I/flutter (22346): sk.fourq.ota_update:
I/flutter (22346): PlatformException(error, Attempt to invoke virtual method 'java.lang.String
I/flutter (22346): java.lang.Object.toString()' on a null object reference, null)
I/flutter (22346):
I/flutter (22346): When the exception was thrown, this was the stack:
I/flutter (22346): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
I/flutter (22346): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
I/flutter (22346): <asynchronous suspension>
I/flutter (22346): #2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:517:29)
I/flutter (22346): #4      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:503:64)`

I use this plug which version is 2.2.1 , but  a PlatformException occurs .Please give some suggests ,thanks.

**Comment by wrl96** [comment]
The "destinationFilename" is required.
`Stream<OtaEvent> execute(String url,
      {String androidProviderAuthority, String destinationFilename})`

**Comment by gxh-apologize** [comment]
@wrl96   The problem has been solved. Thank you.
