### ISSUE TITLE
Downloading not fired in case of download from GoogleDrive

### ISSUE THREAD

**Issue by vasilich6107** [4Q-s-r-o/ota_update#29]
Hi. Thanks for your work!

I found a little issue. In case if I download the file via share link from google drive the `DOWNLOADING` event not fired.

In case of browser download form the same link there is no sign of the whole file size(related to how google streams file to browser) - it seems to be the root cause of the issue.

**Comment by MartinHlavna** [comment]
Should be fixed in 4.0.1

If Content-Length header is missing no progress updates will be published though

**Comment by vasilich6107** [comment]
Thanks for the fix
