### ISSUE TITLE
I add this to my package's pubspec.yaml file

### ISSUE THREAD

**Issue by yinloveone** [4Q-s-r-o/ota_update#34]
D8: Program type already present: androidx.cursoradapter.widget.CursorAdapter$ChangeObserver

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: D:\testmyapp\werong_app\build\app\intermediates\transforms\dexBuilder\debug\91.jar, D:\testmyapp\werong_app\build\app\intermediates\transforms\dexBuilder\debug\73.jar, D:\testmyapp\werong_app\build\app\intermediates\transforms\dexBuilder\debug\88.jar, D:\testmyapp\werong_app\build\app\intermediates\transforms\dexBuilder\debug\67.jar, D:\testmyapp\werong_app\build\app\intermediates\transforms\dexBuilder\debug\82.jar, D:\testmyapp\werong_app\build\app\intermediates\transforms\dexBuilder\debug\58.jar, D:\testmyapp\werong_app\build\app\intermediates\transforms\dexBuilder\debug\94.jar, D:\testmyapp\werong_app\build\app\intermediates\transforms\dexBuilder\debug\85.jar, D:\testmyapp\werong_app\build\app\intermediates\transforms\dexBuilder\debug\70.jar, D:\testmyapp\werong_app\build\app\intermediates\transforms\dexBuilder\debug\97.jar, D:\testmyapp\werong_app\build\app\intermediates\transforms\dexBuilder\debug\64.jar, D:\testmyapp\werong_app\build\app\intermediates\transforms\dexBuilder\debug\76.jar, D:\testmyapp\werong_app\build\app\intermediates\transforms\dexBuilder\debug\61.jar, D:\testmyapp\werong_app\build\app\intermediates\transforms\dexBuilder\debug\79.jar, D:\testmyapp\werong_app\build\app\intermediates\transforms\dexBuilder\debug\14.jar, D:\testmyapp\werong_app\build\app\intermediates\transforms\dexBuilder\debug\19.jar, D:\testmyapp\werong_app\build\app\intermediates\transforms\dexBuilder\debug\4.jar, D:\testmyapp\werong_app\build\app\intermediates\transforms\dexBuilder\debug\9.jar, D:\testmyapp\werong_app\build\app\intermediates\transforms\dexBuilder\debug\31.jar,

**Comment by yinloveone** [comment]
I add classpath 'androidx.lifecycle:lifecycle-extensions:2.2.0' in build.gradle

**Comment by MartinHlavna** [comment]
Hi, thanks for the report

I remember this kind of exceptions when flutter was migrating to AndroidX from old android support libraries. Is your project migrated to AndroidX? 

I could also be conflict with some other libraries. 

> I add classpath 'androidx.lifecycle:lifecycle-extensions:2.2.0' in build.gradle

Do you add it to plugin build.gradle or build.gradle in your project?

**Comment by yinloveone** [comment]
![image](https://user-images.githubusercontent.com/32708172/88614186-c88a6500-d0c1-11ea-840f-24601382df22.png)
