### ISSUE TITLE
There was a problem parsing the package.

### ISSUE THREAD

**Issue by RomeroYang** [4Q-s-r-o/ota_update#35]
In my case, the higher version can be manually installed through a downloaded `.apk` file while the lower version exist, so I assume my `.apk` file was fine.

But when I install the higher version through OTA, it will throw an error after `OtaStatus.DOWNLOADING` and `OtaStatus.INSTALLING`, and after installation failed, I got an `OTA UPDATE SUCCESS`.

The OTA process worked well before, when I was using the `debug signing keys`. And I was using my release signing when I find this error. Maybe there's some issue related to app signing?

**Comment by RomeroYang** [comment]
And I see this error while debugging: `ERROR: unable to delete old apk file before starting OTA`.

Seems to be similar issue with #25 .

**Comment by MartinHlavna** [comment]
Thanks for the report. 

Looks like there is already .apk with given name in downloads folder. Do you provide your own or use the default one?
Maybe your application does not have permission to overwrite that file. If that is the case and it is some old corrupted file or file is signed with different key android will throw an error.

Internally we are using android download manager to download file. There is long standing bug where it will report success even when download failed - which results on starting installation using incorrect file. 

New version of plugin will have ability to provide expected sha 256 checksum when running execute method. That would solve problem with starting installation using incorrect file as it would not probably pass checksum check.

**Comment by MartinHlavna** [comment]
Closing the issue as there is no reply for few months now. Feel free to reopen and provide more information if the problem persists
