### ISSUE TITLE
Suddenly it doesn't work

### ISSUE THREAD

**Issue by ruixue521** [4Q-s-r-o/ota_update#38]
D/FLUTTER OTA(11665): OTA UPDATE ON LISTEN
E/EventChannel#sk.fourq.ota_update(11665): Failed to open event stream
E/EventChannel#sk.fourq.ota_update(11665): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
E/EventChannel#sk.fourq.ota_update(11665): 	at sk.fourq.otaupdate.OtaUpdatePlugin.onListen(OtaUpdatePlugin.java:123)
E/EventChannel#sk.fourq.ota_update(11665): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:188)
E/EventChannel#sk.fourq.ota_update(11665): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:167)
E/EventChannel#sk.fourq.ota_update(11665): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/EventChannel#sk.fourq.ota_update(11665): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/EventChannel#sk.fourq.ota_update(11665): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/EventChannel#sk.fourq.ota_update(11665): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/EventChannel#sk.fourq.ota_update(11665): 	at android.os.Looper.loop(Looper.java:165)
E/EventChannel#sk.fourq.ota_update(11665): 	at android.app.ActivityThread.main(ActivityThread.java:6864)
E/EventChannel#sk.fourq.ota_update(11665): 	at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#sk.fourq.ota_update(11665): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/EventChannel#sk.fourq.ota_update(11665): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

════════ Exception caught by services library ══════════════════════════════════════════════════════
The following PlatformException was thrown while activating platform stream on channel sk.fourq.ota_update:
PlatformException(error, Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference, null)

When the exception was thrown, this was the stack: 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:519:29)
...

**Comment by galtonova** [comment]
I'm getting the same error too. Completely fresh install, just url for download and I get `Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference` error too.

**Comment by MartinHlavna** [comment]
Fixed in 2.4.1 which will be released today. Sorry for inconvenience
