### ISSUE TITLE
When the application package is downloaded, cancel the download and the application exits.

### ISSUE THREAD

**Issue by wk1048387321** [4Q-s-r-o/ota_update#40]
Hi！

When the application package is downloaded, cancel the download and the application exits.

I/OpenGLRenderer(28955): Initialized EGL, version 1.4
E/AndroidRuntime(28955): FATAL EXCEPTION: Thread-7
E/AndroidRuntime(28955): Process: com.******, PID: 28955
E/AndroidRuntime(28955): java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.database.Cursor.moveToFirst()' on a null object reference
E/AndroidRuntime(28955): 	at sk.fourq.otaupdate.OtaUpdatePlugin$3.run(OtaUpdatePlugin.java:293)
E/AndroidRuntime(28955): 	at java.lang.Thread.run(Thread.java:776)
I/Process (28955): Sending signal. PID: 28955 SIG: 9
Lost connection to device.

Flutter 1.17.5 channel stable.
ota_update: ^2.4.1

Thanks！

**Comment by MartinHlavna** [comment]
Hello,

thanks for the report. What exactly "cancel the download" means? Thanks.

**Comment by wk1048387321** [comment]
Cancel the download in the system notification.

**Comment by syedecryptr** [comment]
Same issue when download is canceled from the system notification app crashes with the error.

**Comment by MartinHlavna** [comment]
The problem is that DownloadManager reports canceled downloads as successfull. Added file existence check that should fix some of the crashes. This will however fail if there is file with same name, or cancel does not remove file. 

To verify integrity of the download you can provide sha256 checksum of the file.
