### ISSUE TITLE
replace downloaded file

### ISSUE THREAD

**Issue by chuck2098** [4Q-s-r-o/ota_update#47]
Hi, 
it's not a bug but I would know if it's possible replace the destination file because into download folder there are a lot of apk file with same name.
Thanks

**Comment by zezo357** [comment]
I think you can try and check if the file is downloaded

If the file is found with the same name 
Delete the old one and then download

**Comment by syedecryptr** [comment]
from flutter file present in downloads folder is not deleting.

**Comment by MartinHlavna** [comment]
Sorry for late reply.

What do you mean by "replace the destination file"? 

You can set custom file name by using destinationFilename param. If you execute download with name that already exists, the plugin should automatically delete existing file. 

@syedecryptr This should work out of the box. It is not something special to the plugin.
