### ISSUE TITLE
Android: 5.0.1 No virtual  method checkSelfPermission

### ISSUE THREAD

**Issue by littlesalt** [4Q-s-r-o/ota_update#5]
No virtual method checkSelfPermission(Ljava/lang/String;)I in class Landroid/app/Activity; or its super classes (declaration of 'android.app.Activity' appears in /system/framework/framework.jar)
E/flutter (11380): at sk.fourq.otaupdate.OtaUpdatePlugin.onListen(OtaUpdatePlugin.java:71)

Android: 5.0.1
API:21

**Comment by MartinHlavna** [comment]
Hi,
thanks for the bug report. Did you tried to call ``` flutter clean ``` to see if it solves the problem? If problem still persists after ``` flutter clean ``` please enclose output of  ```flutter doctor -v``` and steps to reproduce.

**Comment by littlesalt** [comment]
ok,it works!
