### ISSUE TITLE
Crash app

### ISSUE THREAD

**Issue by AnOnionz** [4Q-s-r-o/ota_update#51]
exception: ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0,
and crash app when close app use ota update

**Comment by MartinHlavna** [comment]
Hello,

can you provide us with small example project, where we can reproduce the problem?

**Comment by AnOnionz** [comment]
This issue is already working normally. Welcome back and improve this package for the better.
