### ISSUE TITLE
Cannot delete old apk if created by another app

### ISSUE THREAD

**Issue by alexaccaci** [4Q-s-r-o/ota_update#56]
There is a bug on Android 11:
Download with chrome 'https://internal1.4q.sk/flutter_hello_world.apk' and then leave the apk in the download directory.
Now try to run your example it reports: ERROR: unable to delete old apk file before starting OTA.
Then the example fails to install the apk.
Best Regard
Alex

**Comment by MartinHlavna** [comment]
Hello,
i was unable to reproduce this on android 11 device.  Does it work if you delete file from the downloads?

**Comment by aashutoshrathi** [comment]
Yes, it does work when you delete the apk with the same name!

**Comment by MartinHlavna** [comment]
Can you please provide more info? Output from ```flutter doctor```, OS version and device model? 

Thanks

**Comment by MartinHlavna** [comment]
Looks like solution would be to migrate to new storage access framework in android. I don't know when we can allocate time for this. If someone can do it sooner, we will be happy to merge.

**Comment by MartinHlavna** [comment]
Should be fixed in 4.0.1
