### ISSUE TITLE
Version detection

### ISSUE THREAD

**Issue by Lee-BS-AMS** [4Q-s-r-o/ota_update#57]
Hi, how does this plugin determine of the server version is newer than the currently installed version and is there a way to show ‘what’s new’?

**Comment by MartinHlavna** [comment]
Hi,

this is not handled by plugin itself and should be determined before calling execute method. There are many possibilities suitable for many different apps. 

For example for our applications we have dedicated server endpoint for checking for updates. If update is available unique short-lived url is generated for user that is fed to the execute method of the plugin.

**Comment by Lee-BS-AMS** [comment]
Mnay thanks!
