### ISSUE TITLE
App is not getting installed in few devices

### ISSUE THREAD

**Issue by shivanchalaeologic** [4Q-s-r-o/ota_update#59]
when app updating starts in some devices it gets installed while in some devices it is showing a package parsing issue. when the app is updating in the terminal  it shows OTA update success but when I am installing it, it gives package parsing error

![WhatsApp Image 2021-05-17 at 18 53 59](https://user-images.githubusercontent.com/66462755/118512043-1905a880-b750-11eb-9ee7-691417199887.jpeg)

**Comment by sc-ot** [comment]
Is that what you're looking for?

https://github.com/4Q-s-r-o/ota_update/issues/46

**Comment by vivekn4u** [comment]
got the same error and resolved it by implementing **android:requestLegacyExternalStorage="true"** 
but even after installing the app is not getting updated, do you know why?


`<application
        android:requestLegacyExternalStorage="true"
        android:allowBackup="false"
        android:name=".Application"
        android:label="Live 2D"
        android:icon="@mipmap/ic_launcher">`

**Comment by shivanchalaeologic** [comment]
now the error is resolved after following all the necessary steps you need to define the file path, however, it works fine without defining it but on some devices, it does not, so better you do this. Now I am closing this issue.
