### ISSUE TITLE
not working ~~ 

### ISSUE THREAD

**Issue by bakboem** [4Q-s-r-o/ota_update#62]
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
A problem occurred configuring project ':ota_update'.                   
> Could not resolve all artifacts for configuration ':ota_update:classpath'.
   > Could not resolve com.android.tools.build:gradle:3.3.1.            
     Required by:                                                       
         project :ota_update                                            
      > Could not resolve com.android.tools.build:gradle:3.3.1.         
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.3.1/gradle-3.3.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.3.1/gradle-3.3.1.pom'.
               > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.android.tools.build:gradle:3.3.1.         
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.3.1/gradle-3.3.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.3.1/gradle-3.3.1.pom'.
               > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> Could not get unknown property 'android' for project ':ota_update' of type org.gradle.api.Project.
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org

**Comment by MartinHlavna** [comment]
Hi,

version 3.1.1 should solve this.

**Comment by bakboem** [comment]
> Hi,
> 
> version 3.1.1 should solve this.

thanks bro~!

**Comment by hammadcc** [comment]
hey,
is it solved ? i'm still facing the same issue.
