### ISSUE TITLE
Cant Download status 400

### ISSUE THREAD

**Issue by hoangtuan2402** [4Q-s-r-o/ota_update#65]
STREAM OPENED
 DOWNLOAD STARTING
 DOWNLOAD STARTED WITH ID 52
TRACK DOWNLOAD STARTED 52
 TRACK DOWNLOAD THREAD STARTED 52
 OTA UPDATE PENDING 
 STREAM CLOSED
 OTA UPDATE FAILURE: 400

its All of my Logs, I flowed by instruction but it don't download file @@

**Comment by MartinHlavna** [comment]
Hi,

looks like it failed on HTTP 400 Bad Request. Can you share your code?

**Comment by MartinHlavna** [comment]
Closing because of no response from reporter. 400 indicates error response from server. Please note if your server requires some headers (for example Authorization, ... ) you can easily pass them to plugin via headers parameter.
