### ISSUE TITLE
Pass a header to destination.

### ISSUE THREAD

**Issue by Dichill** [4Q-s-r-o/ota_update#69]
as the name suggest, is there a way to pass a Authorization Header that requires token to retrieve the file? Or should I simply make a http.get with a header and pass that to .execute()?

**Comment by Dichill** [comment]
okay I'm dumb, I checked the code of OtaUpdate().execute() and you can actually pass a header parameter.

e.g.

```
OtaUpdate().execute(
          'test.apk',
          headers: {"Authorization": "token $gToken"}).listen(
        (OtaEvent event) {
          setState(() => {
                currentEvent = event,
              });
        },
      );
```

**Comment by MartinHlavna** [comment]
Closing as it looks like, you have resolved issue yourself. :)
