### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by iamuvirus** [4Q-s-r-o/ota_update#70]
![image](https://user-images.githubusercontent.com/28762028/145933901-47341809-a9e1-4872-91b1-93b3ab6c0813.png)
![image](https://user-images.githubusercontent.com/28762028/145933949-1b7c0d21-0920-4aa1-94a9-44f1402266a7.png)
![image](https://user-images.githubusercontent.com/28762028/145934322-326f79f2-f5f0-4c9c-8376-c7db9b81ce38.png)

what's wrong?

**Comment by MartinHlavna** [comment]
Hello, can you try to move file somewhere accessible (e.g. downloads folder) and try to execute it manually? Maybe  the file is corrupted.

**Comment by zuwuko** [comment]
The example continuously downloads and downloads and re downloads the APK over and over like in a loop until you click INSTALL. This cant be right..?

**Comment by MartinHlavna** [comment]
@JeongEEE Hello. Just to be sure, are you using 4.0.0+ version of the package? There might be possibility that application does not have permissions for package. Since 4.0.0+ it shouldn't be issue thought. 

It is kinda unfortunate that @iamuvirus did not reply since we can see he is using 4.0.1. It would help us to better understand problem.

> The file name is always the same, is this the cause?

No, we using it just like that in our production apps.

**Comment by robman70** [comment]
Now I'm even more confused: after hours and hours of searching and trying, I've added these two lines to my AndroidManifest.xml:

<uses-permission android: name = "android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android: name = "android.permission.REQUEST_INSTALL_PACKAGES" />

and the update started working!

The strangest thing is that then I commented those two lines and ... now it continues to work (I always test in debug using an emulator). I don't understand why and this worries me a little.

But now I notice another problem and I wonder if I have the wrong approach: I would like to do the automatic update every time the app is started (then the user must confirm the installation, of course) but there is no control to avoid downloading twice the same apk? The app updates at every start ... or rather, every two.
a - At a first start it downloads the file, requests the installation and updates the package.
b - The app then restarts by itself, downloads the file again but no installation is started.
c - I close the app, restart it and everything restarts from point a

Some time ago, in an app that I had developed with Cordova, I had implemented a similar mechanism just to download new content of the app (not the whole apk ... it was obviously a hybrid app), I did a test on the date and time of creating the remote file and comparing it with the local cached copy, to avoid downloading the same file multiple times ... isn't there a similar system here?
How can I avoid downloading and even installing the same version of the app several times?

Thank you

**Comment by robman70** [comment]
Sorry ... wrong copy / paste.

Here are the two lines I was referring to:

& lt; android usage permission: name = "android.permission.WRITE_EXTERNAL_STORAGE" / & gt;
& lt; use-permission android: name = "android.permission.REQUEST_INSTALL_PACKAGES" / & gt;

Thanks for the reply also for the other question.

Got a suggestion to use your plugin in a main.dart based on stateless widget? Your example uses a statefull one... I tried to use a statefull wrapper (which calls the main stateless widget) but I may have something wrong ... I can't get it to work.

Thank you

**Comment by MartinHlavna** [comment]
permission makes sense. I will add it to the documentation later.

```ota_update``` should not care much for the Stateless/Statefull. But where are you calling execute method?

much of this depends on how your app works - if you always need internet connection, or if you want to support offline mode...

**Comment by robman70** [comment]
In fact it seems that those additional permissions have also solved the problems in the app I am developing and I found the logic error in starting the download of the update, thanks.

Have a nice day

**Comment by CaptainKant** [comment]
With the same code, and this two lines of permission, I have this problem on a Android device (warehouse Zebra pointing scanner) but it works very well on my smartphone.
So I think the bug is still there
