### ISSUE TITLE
It keeps saying that the certificate cannot be found

### ISSUE THREAD

**Issue by luo353010979** [4Q-s-r-o/ota_update#74]
E/FLUTTER OTA: ERROR: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
    javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by MartinHlavna** [comment]
Hello,
are u using self signed certificate for http or untrusted root? This would have to be configured in android security config.

https://developer.android.com/training/articles/security-config
