### ISSUE TITLE
Parse Error on Android 6.0

### ISSUE THREAD

**Issue by FlippedOvO** [4Q-s-r-o/ota_update#75]
I know it's a permissions issue.
but I don't know how to fix it .
Someone tell me ?

**Comment by MartinHlavna** [comment]
Hello,

maybe try to apply fix from https://github.com/4Q-s-r-o/ota_update/issues/70#issuecomment-1040074653
I am going to add needed permissions to readme right now.

**Comment by MartinHlavna** [comment]
README si updated.
