### ISSUE TITLE
低版本Android手机下载成功但是安装失败

### ISSUE THREAD

**Issue by wufengfeilong** [4Q-s-r-o/ota_update#76]
现象：下载成功后，跳转安装界面时 显示 解析包时出现问题
感觉可能是 低版本手机性能低 虽然下载完成 但是还没关闭stream 就进行安装 导致没法解析安装包。
测试手机 红米Note2 Android5.0.2

**Comment by ethael** [comment]
Communication language for issues is English. Create new issue with all necessary details and possibly a reproduction procedure. Thank you.

**Comment by yjt1216** [comment]
> Communication language for issues is English. Create new issue with all necessary details and possibly a reproduction procedure. Thank you.

请问你解决了吗？我是 android 6.0 error
