### ISSUE TITLE
Does it support multi-threaded downloading of updates?

### ISSUE THREAD

**Issue by luomo-pro** [4Q-s-r-o/ota_update#77]
Some download addresses are particularly slow in single-threaded downloads, but particularly fast when using tools such as "Internet Download Manager" that support multi-threaded downloads.
I tried, it seems that ota_update does not support multi-threading, the download speed is very slow.
Is there a solution for this?

**Comment by ethael** [comment]
this plugin uses standard http client library okhttp. You can check the docs regarding implementation details.

AFAIK, download of one file using http protocol is always single thread. You make request and then you are getting one response with body where file data is stored.. The only way I can think of to achieve paralel download is chunking. But this must be supported on both server and client side.

If you like, you can try implement such feature. It must work both ways of course.
