### ISSUE TITLE
Hello boss, I would like to consult your OTA_Update library. How many Android systems do you support since?

### ISSUE THREAD

**Issue by WangYiOS** [4Q-s-r-o/ota_update#84]
Hello boss, I would like to consult your OTA_Update library. How many Android systems do you support since? I checked your file. I can't find it. But the Internet says it started with Android 6.0. I'm here to prove it to you.

============

大佬你好，我咨询下您的ota_update库，支持安卓系统多少开始的？我看了下您的文档，没找到。但是网上说是从安卓6.0开始的。来这里像大佬你求证下。

**Comment by MartinHlavna** [comment]
Hello,
minSdk in build.gradle is for [API level](https://developer.android.com/studio/releases/platforms) 16, but there is no extensive testing for old Android versions. We have code in place that executes installation  differently for [API level](https://developer.android.com/studio/releases/platforms) lower than 24.

> But the Internet says it started with Android 6.0.

You are maybe mistaking this for system OTA Update that is for updating operating system itself. This library is just package downloader and installer for people that can't publish their application in Google Play (or another app store) but still want ability to update application.

**Comment by MartinHlavna** [comment]
Closing issue, since no new information has been requested.
