### ISSUE TITLE
E/AndroidRuntime(21511): java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.example.app.ota_update_provider

### ISSUE THREAD

**Issue by ElegantCrab** [4Q-s-r-o/ota_update#88]
Is there a way to solve this error?

I'm receiving this file from a GET endpoint on a custom C# API I have

**Comment by ElegantCrab** [comment]
Here's the full error

D/FLUTTER OTA(21511): Download is complete
[log] DOWNLOADING
D/AndroidRuntime(21511): Shutting down VM
[log] DOWNLOADING
E/AndroidRuntime(21511): FATAL EXCEPTION: main
E/AndroidRuntime(21511): Process: com.example.g3pipas, PID: 21511
E/AndroidRuntime(21511): java.lang.IllegalArgumentException: Couldn't find meta-data for provider with authority com.example.app.ota_update_provider
E/AndroidRuntime(21511): 	at androidx.core.content.FileProvider.getFileProviderPathsMetaData(FileProvider.java:664)
E/AndroidRuntime(21511): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:695)
E/AndroidRuntime(21511): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:645)
E/AndroidRuntime(21511): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:449)
E/AndroidRuntime(21511): 	at sk.fourq.otaupdate.OtaUpdatePlugin.executeInstallation(OtaUpdatePlugin.java:306)
E/AndroidRuntime(21511): 	at sk.fourq.otaupdate.OtaUpdatePlugin.access$200(OtaUpdatePlugin.java:47)
E/AndroidRuntime(21511): 	at sk.fourq.otaupdate.OtaUpdatePlugin$2.run(OtaUpdatePlugin.java:286)
E/AndroidRuntime(21511): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(21511): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(21511): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(21511): 	at android.app.ActivityThread.main(ActivityThread.java:7700)
E/AndroidRuntime(21511): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21511): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
E/AndroidRuntime(21511): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
Lost connection to device.

**Comment by ElegantCrab** [comment]
Just noticed this happens due to incorrect AndroidManifest permissions.

Closing the issue

**Comment by MikolajPorebny** [comment]
>Just noticed this happens due to incorrect AndroidManifest permissions.

Could you tell more info about this? It may help someone...
