### ISSUE TITLE
lint warning regarding PluginRegistry Depreciation

### ISSUE THREAD

**Issue by christopherowen** [4Q-s-r-o/ota_update#98]
I'm receiving this error on release build with lint enabled.

```
/opt/homebrew/Caskroom/flutter/3.7.0/flutter/.pub-cache/hosted/pub.dev/ota_update-4.0.2/android/src/main/java/sk/fourq/otaupdate/OtaUpdatePlugin.java:81: warning: [deprecation] Registrar in PluginRegistry has been deprecated
    public static void registerWith(io.flutter.plugin.common.PluginRegistry.Registrar registrar) {
                                                                           ^
1 warning
```

My searching on the topic lead me to this page, but I'm a little out of my depth: 

- https://api.flutter.dev/javadoc/io/flutter/plugin/common/PluginRegistry.html
- https://docs.flutter.dev/development/platform-integration/android/plugin-api-migration

**Comment by MartinHlavna** [comment]
Hello,
we still support old  APIs therefore this produces the lint warning.  We are planning to remove backwards compatibility with old flutter soon, so this will be fixed in one of the upcoming releases.

**Comment by MartinHlavna** [comment]
We are dropping support for Android Embedding v1 in ```5.0.0```. Warning should disappear.
